name: Cyber Intelligence Curator

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 pyyaml

      - name: run scraper 
        run: python scraper.py 
        
      - name: clean news 
        run: python cleaner.py 
        
      - name: remove duplicates 
        run: python deduplicator.py 
        
      - name: classify news 
        run: python classifier.py 
        
      - name: select best news 
        run: python selector.py 
        
      - name: build newsletter prompt 
        run: python newsletter.py
        
      - name: commit results 
        run: | 
         git config --global user.name "cyber-agent" 
         git config --global user.email "agent@github.com" 
         git add . 
         if git diff --staged --quiet; then
              echo "No changes to commit"
         else
             git commit -m "weekly cyber intel update"
             git push
         fi
